### PR TITLE
Suggested to delete as handled by auto-prefixing

### PR DESCRIPTION
**Pull request by terryupton**
Most people use auto prefixes so suggested we remove this mixin.

### CODE REVIEW

**Comment by terryupton** [comment]
Dunno if I am doing any of this correctly Stu. Sorry. Some pull requests I have made.

**Comment by sturobson** [comment]
Hi @terryupton can you remove the _hover.scss from this PR, there's a bit I want to change in it.

**Comment by terryupton** [comment]
Removed Hover. Do you want me to add it as a separate pull request?

**Comment by sturobson** [comment]
Hi Terry, 

yeah a separate pull request, can you remove it from here again as if I merge it'll add it. I want to discuss further on a separate PR.

Stu

**Pull request merged**
